// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PersonProto.proto

package by.next.way.protobuf.kotlin;

/**
 * Protobuf type {@code PersonProto}
 */
public  final class PersonProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PersonProto)
    PersonProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PersonProto.newBuilder() to construct.
  private PersonProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PersonProto() {
    firstName_ = "";
    lastName_ = "";
    emailAddress_ = "";
    homeAddress_ = "";
    phoneNumbers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PersonProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            firstName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            lastName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            emailAddress_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            homeAddress_ = s;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) != 0)) {
              phoneNumbers_ = new java.util.ArrayList<by.next.way.protobuf.kotlin.PersonProto.PhoneNumber>();
              mutable_bitField0_ |= 0x00000010;
            }
            phoneNumbers_.add(
                input.readMessage(by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) != 0)) {
        phoneNumbers_ = java.util.Collections.unmodifiableList(phoneNumbers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return by.next.way.protobuf.kotlin.OuterPersonProto.internal_static_PersonProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return by.next.way.protobuf.kotlin.OuterPersonProto.internal_static_PersonProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            by.next.way.protobuf.kotlin.PersonProto.class, by.next.way.protobuf.kotlin.PersonProto.Builder.class);
  }

  public interface PhoneNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PersonProto.PhoneNumber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 areaCode = 1;</code>
     */
    int getAreaCode();

    /**
     * <code>int32 phoneNumber = 2;</code>
     */
    int getPhoneNumber();
  }
  /**
   * Protobuf type {@code PersonProto.PhoneNumber}
   */
  public  static final class PhoneNumber extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PersonProto.PhoneNumber)
      PhoneNumberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PhoneNumber.newBuilder() to construct.
    private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PhoneNumber() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PhoneNumber(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              areaCode_ = input.readInt32();
              break;
            }
            case 16: {

              phoneNumber_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return by.next.way.protobuf.kotlin.OuterPersonProto.internal_static_PersonProto_PhoneNumber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return by.next.way.protobuf.kotlin.OuterPersonProto.internal_static_PersonProto_PhoneNumber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.class, by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.Builder.class);
    }

    public static final int AREACODE_FIELD_NUMBER = 1;
    private int areaCode_;
    /**
     * <code>int32 areaCode = 1;</code>
     */
    public int getAreaCode() {
      return areaCode_;
    }

    public static final int PHONENUMBER_FIELD_NUMBER = 2;
    private int phoneNumber_;
    /**
     * <code>int32 phoneNumber = 2;</code>
     */
    public int getPhoneNumber() {
      return phoneNumber_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (areaCode_ != 0) {
        output.writeInt32(1, areaCode_);
      }
      if (phoneNumber_ != 0) {
        output.writeInt32(2, phoneNumber_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (areaCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, areaCode_);
      }
      if (phoneNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, phoneNumber_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof by.next.way.protobuf.kotlin.PersonProto.PhoneNumber)) {
        return super.equals(obj);
      }
      by.next.way.protobuf.kotlin.PersonProto.PhoneNumber other = (by.next.way.protobuf.kotlin.PersonProto.PhoneNumber) obj;

      if (getAreaCode()
          != other.getAreaCode()) return false;
      if (getPhoneNumber()
          != other.getPhoneNumber()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AREACODE_FIELD_NUMBER;
      hash = (53 * hash) + getAreaCode();
      hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static by.next.way.protobuf.kotlin.PersonProto.PhoneNumber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static by.next.way.protobuf.kotlin.PersonProto.PhoneNumber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static by.next.way.protobuf.kotlin.PersonProto.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static by.next.way.protobuf.kotlin.PersonProto.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static by.next.way.protobuf.kotlin.PersonProto.PhoneNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static by.next.way.protobuf.kotlin.PersonProto.PhoneNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static by.next.way.protobuf.kotlin.PersonProto.PhoneNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static by.next.way.protobuf.kotlin.PersonProto.PhoneNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static by.next.way.protobuf.kotlin.PersonProto.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static by.next.way.protobuf.kotlin.PersonProto.PhoneNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static by.next.way.protobuf.kotlin.PersonProto.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static by.next.way.protobuf.kotlin.PersonProto.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(by.next.way.protobuf.kotlin.PersonProto.PhoneNumber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PersonProto.PhoneNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PersonProto.PhoneNumber)
        by.next.way.protobuf.kotlin.PersonProto.PhoneNumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return by.next.way.protobuf.kotlin.OuterPersonProto.internal_static_PersonProto_PhoneNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return by.next.way.protobuf.kotlin.OuterPersonProto.internal_static_PersonProto_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.class, by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.Builder.class);
      }

      // Construct using by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        areaCode_ = 0;

        phoneNumber_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return by.next.way.protobuf.kotlin.OuterPersonProto.internal_static_PersonProto_PhoneNumber_descriptor;
      }

      @java.lang.Override
      public by.next.way.protobuf.kotlin.PersonProto.PhoneNumber getDefaultInstanceForType() {
        return by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.getDefaultInstance();
      }

      @java.lang.Override
      public by.next.way.protobuf.kotlin.PersonProto.PhoneNumber build() {
        by.next.way.protobuf.kotlin.PersonProto.PhoneNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public by.next.way.protobuf.kotlin.PersonProto.PhoneNumber buildPartial() {
        by.next.way.protobuf.kotlin.PersonProto.PhoneNumber result = new by.next.way.protobuf.kotlin.PersonProto.PhoneNumber(this);
        result.areaCode_ = areaCode_;
        result.phoneNumber_ = phoneNumber_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof by.next.way.protobuf.kotlin.PersonProto.PhoneNumber) {
          return mergeFrom((by.next.way.protobuf.kotlin.PersonProto.PhoneNumber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(by.next.way.protobuf.kotlin.PersonProto.PhoneNumber other) {
        if (other == by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.getDefaultInstance()) return this;
        if (other.getAreaCode() != 0) {
          setAreaCode(other.getAreaCode());
        }
        if (other.getPhoneNumber() != 0) {
          setPhoneNumber(other.getPhoneNumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        by.next.way.protobuf.kotlin.PersonProto.PhoneNumber parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (by.next.way.protobuf.kotlin.PersonProto.PhoneNumber) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int areaCode_ ;
      /**
       * <code>int32 areaCode = 1;</code>
       */
      public int getAreaCode() {
        return areaCode_;
      }
      /**
       * <code>int32 areaCode = 1;</code>
       */
      public Builder setAreaCode(int value) {
        
        areaCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 areaCode = 1;</code>
       */
      public Builder clearAreaCode() {
        
        areaCode_ = 0;
        onChanged();
        return this;
      }

      private int phoneNumber_ ;
      /**
       * <code>int32 phoneNumber = 2;</code>
       */
      public int getPhoneNumber() {
        return phoneNumber_;
      }
      /**
       * <code>int32 phoneNumber = 2;</code>
       */
      public Builder setPhoneNumber(int value) {
        
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 phoneNumber = 2;</code>
       */
      public Builder clearPhoneNumber() {
        
        phoneNumber_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PersonProto.PhoneNumber)
    }

    // @@protoc_insertion_point(class_scope:PersonProto.PhoneNumber)
    private static final by.next.way.protobuf.kotlin.PersonProto.PhoneNumber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new by.next.way.protobuf.kotlin.PersonProto.PhoneNumber();
    }

    public static by.next.way.protobuf.kotlin.PersonProto.PhoneNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PhoneNumber>
        PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
      @java.lang.Override
      public PhoneNumber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhoneNumber(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PhoneNumber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public by.next.way.protobuf.kotlin.PersonProto.PhoneNumber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int FIRSTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object firstName_;
  /**
   * <code>string firstName = 1;</code>
   */
  public java.lang.String getFirstName() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firstName_ = s;
      return s;
    }
  }
  /**
   * <code>string firstName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFirstNameBytes() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object lastName_;
  /**
   * <code>string lastName = 2;</code>
   */
  public java.lang.String getLastName() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastName_ = s;
      return s;
    }
  }
  /**
   * <code>string lastName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLastNameBytes() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAILADDRESS_FIELD_NUMBER = 3;
  private volatile java.lang.Object emailAddress_;
  /**
   * <code>string emailAddress = 3;</code>
   */
  public java.lang.String getEmailAddress() {
    java.lang.Object ref = emailAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      emailAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string emailAddress = 3;</code>
   */
  public com.google.protobuf.ByteString
      getEmailAddressBytes() {
    java.lang.Object ref = emailAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      emailAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOMEADDRESS_FIELD_NUMBER = 4;
  private volatile java.lang.Object homeAddress_;
  /**
   * <code>string homeAddress = 4;</code>
   */
  public java.lang.String getHomeAddress() {
    java.lang.Object ref = homeAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      homeAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string homeAddress = 4;</code>
   */
  public com.google.protobuf.ByteString
      getHomeAddressBytes() {
    java.lang.Object ref = homeAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      homeAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONENUMBERS_FIELD_NUMBER = 5;
  private java.util.List<by.next.way.protobuf.kotlin.PersonProto.PhoneNumber> phoneNumbers_;
  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
   */
  public java.util.List<by.next.way.protobuf.kotlin.PersonProto.PhoneNumber> getPhoneNumbersList() {
    return phoneNumbers_;
  }
  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
   */
  public java.util.List<? extends by.next.way.protobuf.kotlin.PersonProto.PhoneNumberOrBuilder> 
      getPhoneNumbersOrBuilderList() {
    return phoneNumbers_;
  }
  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
   */
  public int getPhoneNumbersCount() {
    return phoneNumbers_.size();
  }
  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
   */
  public by.next.way.protobuf.kotlin.PersonProto.PhoneNumber getPhoneNumbers(int index) {
    return phoneNumbers_.get(index);
  }
  /**
   * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
   */
  public by.next.way.protobuf.kotlin.PersonProto.PhoneNumberOrBuilder getPhoneNumbersOrBuilder(
      int index) {
    return phoneNumbers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFirstNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstName_);
    }
    if (!getLastNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastName_);
    }
    if (!getEmailAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, emailAddress_);
    }
    if (!getHomeAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, homeAddress_);
    }
    for (int i = 0; i < phoneNumbers_.size(); i++) {
      output.writeMessage(5, phoneNumbers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFirstNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstName_);
    }
    if (!getLastNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastName_);
    }
    if (!getEmailAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, emailAddress_);
    }
    if (!getHomeAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, homeAddress_);
    }
    for (int i = 0; i < phoneNumbers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, phoneNumbers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof by.next.way.protobuf.kotlin.PersonProto)) {
      return super.equals(obj);
    }
    by.next.way.protobuf.kotlin.PersonProto other = (by.next.way.protobuf.kotlin.PersonProto) obj;

    if (!getFirstName()
        .equals(other.getFirstName())) return false;
    if (!getLastName()
        .equals(other.getLastName())) return false;
    if (!getEmailAddress()
        .equals(other.getEmailAddress())) return false;
    if (!getHomeAddress()
        .equals(other.getHomeAddress())) return false;
    if (!getPhoneNumbersList()
        .equals(other.getPhoneNumbersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getFirstName().hashCode();
    hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getLastName().hashCode();
    hash = (37 * hash) + EMAILADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getEmailAddress().hashCode();
    hash = (37 * hash) + HOMEADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getHomeAddress().hashCode();
    if (getPhoneNumbersCount() > 0) {
      hash = (37 * hash) + PHONENUMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumbersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static by.next.way.protobuf.kotlin.PersonProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static by.next.way.protobuf.kotlin.PersonProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static by.next.way.protobuf.kotlin.PersonProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static by.next.way.protobuf.kotlin.PersonProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static by.next.way.protobuf.kotlin.PersonProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static by.next.way.protobuf.kotlin.PersonProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static by.next.way.protobuf.kotlin.PersonProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static by.next.way.protobuf.kotlin.PersonProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static by.next.way.protobuf.kotlin.PersonProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static by.next.way.protobuf.kotlin.PersonProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static by.next.way.protobuf.kotlin.PersonProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static by.next.way.protobuf.kotlin.PersonProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(by.next.way.protobuf.kotlin.PersonProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PersonProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PersonProto)
      by.next.way.protobuf.kotlin.PersonProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return by.next.way.protobuf.kotlin.OuterPersonProto.internal_static_PersonProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return by.next.way.protobuf.kotlin.OuterPersonProto.internal_static_PersonProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              by.next.way.protobuf.kotlin.PersonProto.class, by.next.way.protobuf.kotlin.PersonProto.Builder.class);
    }

    // Construct using by.next.way.protobuf.kotlin.PersonProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPhoneNumbersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      firstName_ = "";

      lastName_ = "";

      emailAddress_ = "";

      homeAddress_ = "";

      if (phoneNumbersBuilder_ == null) {
        phoneNumbers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        phoneNumbersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return by.next.way.protobuf.kotlin.OuterPersonProto.internal_static_PersonProto_descriptor;
    }

    @java.lang.Override
    public by.next.way.protobuf.kotlin.PersonProto getDefaultInstanceForType() {
      return by.next.way.protobuf.kotlin.PersonProto.getDefaultInstance();
    }

    @java.lang.Override
    public by.next.way.protobuf.kotlin.PersonProto build() {
      by.next.way.protobuf.kotlin.PersonProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public by.next.way.protobuf.kotlin.PersonProto buildPartial() {
      by.next.way.protobuf.kotlin.PersonProto result = new by.next.way.protobuf.kotlin.PersonProto(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.firstName_ = firstName_;
      result.lastName_ = lastName_;
      result.emailAddress_ = emailAddress_;
      result.homeAddress_ = homeAddress_;
      if (phoneNumbersBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          phoneNumbers_ = java.util.Collections.unmodifiableList(phoneNumbers_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.phoneNumbers_ = phoneNumbers_;
      } else {
        result.phoneNumbers_ = phoneNumbersBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof by.next.way.protobuf.kotlin.PersonProto) {
        return mergeFrom((by.next.way.protobuf.kotlin.PersonProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(by.next.way.protobuf.kotlin.PersonProto other) {
      if (other == by.next.way.protobuf.kotlin.PersonProto.getDefaultInstance()) return this;
      if (!other.getFirstName().isEmpty()) {
        firstName_ = other.firstName_;
        onChanged();
      }
      if (!other.getLastName().isEmpty()) {
        lastName_ = other.lastName_;
        onChanged();
      }
      if (!other.getEmailAddress().isEmpty()) {
        emailAddress_ = other.emailAddress_;
        onChanged();
      }
      if (!other.getHomeAddress().isEmpty()) {
        homeAddress_ = other.homeAddress_;
        onChanged();
      }
      if (phoneNumbersBuilder_ == null) {
        if (!other.phoneNumbers_.isEmpty()) {
          if (phoneNumbers_.isEmpty()) {
            phoneNumbers_ = other.phoneNumbers_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePhoneNumbersIsMutable();
            phoneNumbers_.addAll(other.phoneNumbers_);
          }
          onChanged();
        }
      } else {
        if (!other.phoneNumbers_.isEmpty()) {
          if (phoneNumbersBuilder_.isEmpty()) {
            phoneNumbersBuilder_.dispose();
            phoneNumbersBuilder_ = null;
            phoneNumbers_ = other.phoneNumbers_;
            bitField0_ = (bitField0_ & ~0x00000010);
            phoneNumbersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPhoneNumbersFieldBuilder() : null;
          } else {
            phoneNumbersBuilder_.addAllMessages(other.phoneNumbers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      by.next.way.protobuf.kotlin.PersonProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (by.next.way.protobuf.kotlin.PersonProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object firstName_ = "";
    /**
     * <code>string firstName = 1;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string firstName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string firstName = 1;</code>
     */
    public Builder setFirstName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      firstName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string firstName = 1;</code>
     */
    public Builder clearFirstName() {
      
      firstName_ = getDefaultInstance().getFirstName();
      onChanged();
      return this;
    }
    /**
     * <code>string firstName = 1;</code>
     */
    public Builder setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      firstName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastName_ = "";
    /**
     * <code>string lastName = 2;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastName = 2;</code>
     */
    public Builder setLastName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lastName = 2;</code>
     */
    public Builder clearLastName() {
      
      lastName_ = getDefaultInstance().getLastName();
      onChanged();
      return this;
    }
    /**
     * <code>string lastName = 2;</code>
     */
    public Builder setLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object emailAddress_ = "";
    /**
     * <code>string emailAddress = 3;</code>
     */
    public java.lang.String getEmailAddress() {
      java.lang.Object ref = emailAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emailAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string emailAddress = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailAddressBytes() {
      java.lang.Object ref = emailAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emailAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string emailAddress = 3;</code>
     */
    public Builder setEmailAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      emailAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string emailAddress = 3;</code>
     */
    public Builder clearEmailAddress() {
      
      emailAddress_ = getDefaultInstance().getEmailAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string emailAddress = 3;</code>
     */
    public Builder setEmailAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      emailAddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object homeAddress_ = "";
    /**
     * <code>string homeAddress = 4;</code>
     */
    public java.lang.String getHomeAddress() {
      java.lang.Object ref = homeAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        homeAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string homeAddress = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHomeAddressBytes() {
      java.lang.Object ref = homeAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        homeAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string homeAddress = 4;</code>
     */
    public Builder setHomeAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      homeAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string homeAddress = 4;</code>
     */
    public Builder clearHomeAddress() {
      
      homeAddress_ = getDefaultInstance().getHomeAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string homeAddress = 4;</code>
     */
    public Builder setHomeAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      homeAddress_ = value;
      onChanged();
      return this;
    }

    private java.util.List<by.next.way.protobuf.kotlin.PersonProto.PhoneNumber> phoneNumbers_ =
      java.util.Collections.emptyList();
    private void ensurePhoneNumbersIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        phoneNumbers_ = new java.util.ArrayList<by.next.way.protobuf.kotlin.PersonProto.PhoneNumber>(phoneNumbers_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        by.next.way.protobuf.kotlin.PersonProto.PhoneNumber, by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.Builder, by.next.way.protobuf.kotlin.PersonProto.PhoneNumberOrBuilder> phoneNumbersBuilder_;

    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public java.util.List<by.next.way.protobuf.kotlin.PersonProto.PhoneNumber> getPhoneNumbersList() {
      if (phoneNumbersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phoneNumbers_);
      } else {
        return phoneNumbersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public int getPhoneNumbersCount() {
      if (phoneNumbersBuilder_ == null) {
        return phoneNumbers_.size();
      } else {
        return phoneNumbersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public by.next.way.protobuf.kotlin.PersonProto.PhoneNumber getPhoneNumbers(int index) {
      if (phoneNumbersBuilder_ == null) {
        return phoneNumbers_.get(index);
      } else {
        return phoneNumbersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public Builder setPhoneNumbers(
        int index, by.next.way.protobuf.kotlin.PersonProto.PhoneNumber value) {
      if (phoneNumbersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.set(index, value);
        onChanged();
      } else {
        phoneNumbersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public Builder setPhoneNumbers(
        int index, by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.Builder builderForValue) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.set(index, builderForValue.build());
        onChanged();
      } else {
        phoneNumbersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public Builder addPhoneNumbers(by.next.way.protobuf.kotlin.PersonProto.PhoneNumber value) {
      if (phoneNumbersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(value);
        onChanged();
      } else {
        phoneNumbersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public Builder addPhoneNumbers(
        int index, by.next.way.protobuf.kotlin.PersonProto.PhoneNumber value) {
      if (phoneNumbersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(index, value);
        onChanged();
      } else {
        phoneNumbersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public Builder addPhoneNumbers(
        by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.Builder builderForValue) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(builderForValue.build());
        onChanged();
      } else {
        phoneNumbersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public Builder addPhoneNumbers(
        int index, by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.Builder builderForValue) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(index, builderForValue.build());
        onChanged();
      } else {
        phoneNumbersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public Builder addAllPhoneNumbers(
        java.lang.Iterable<? extends by.next.way.protobuf.kotlin.PersonProto.PhoneNumber> values) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phoneNumbers_);
        onChanged();
      } else {
        phoneNumbersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public Builder clearPhoneNumbers() {
      if (phoneNumbersBuilder_ == null) {
        phoneNumbers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        phoneNumbersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public Builder removePhoneNumbers(int index) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.remove(index);
        onChanged();
      } else {
        phoneNumbersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.Builder getPhoneNumbersBuilder(
        int index) {
      return getPhoneNumbersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public by.next.way.protobuf.kotlin.PersonProto.PhoneNumberOrBuilder getPhoneNumbersOrBuilder(
        int index) {
      if (phoneNumbersBuilder_ == null) {
        return phoneNumbers_.get(index);  } else {
        return phoneNumbersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public java.util.List<? extends by.next.way.protobuf.kotlin.PersonProto.PhoneNumberOrBuilder> 
         getPhoneNumbersOrBuilderList() {
      if (phoneNumbersBuilder_ != null) {
        return phoneNumbersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phoneNumbers_);
      }
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.Builder addPhoneNumbersBuilder() {
      return getPhoneNumbersFieldBuilder().addBuilder(
          by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.getDefaultInstance());
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.Builder addPhoneNumbersBuilder(
        int index) {
      return getPhoneNumbersFieldBuilder().addBuilder(
          index, by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.getDefaultInstance());
    }
    /**
     * <code>repeated .PersonProto.PhoneNumber phoneNumbers = 5;</code>
     */
    public java.util.List<by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.Builder> 
         getPhoneNumbersBuilderList() {
      return getPhoneNumbersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        by.next.way.protobuf.kotlin.PersonProto.PhoneNumber, by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.Builder, by.next.way.protobuf.kotlin.PersonProto.PhoneNumberOrBuilder> 
        getPhoneNumbersFieldBuilder() {
      if (phoneNumbersBuilder_ == null) {
        phoneNumbersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            by.next.way.protobuf.kotlin.PersonProto.PhoneNumber, by.next.way.protobuf.kotlin.PersonProto.PhoneNumber.Builder, by.next.way.protobuf.kotlin.PersonProto.PhoneNumberOrBuilder>(
                phoneNumbers_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        phoneNumbers_ = null;
      }
      return phoneNumbersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PersonProto)
  }

  // @@protoc_insertion_point(class_scope:PersonProto)
  private static final by.next.way.protobuf.kotlin.PersonProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new by.next.way.protobuf.kotlin.PersonProto();
  }

  public static by.next.way.protobuf.kotlin.PersonProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersonProto>
      PARSER = new com.google.protobuf.AbstractParser<PersonProto>() {
    @java.lang.Override
    public PersonProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PersonProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PersonProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PersonProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public by.next.way.protobuf.kotlin.PersonProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

