version: '3.3'

services:

  rabbitmq:
    image: bitnami/rabbitmq:latest
    restart: always
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
    ports:
      - "15672:15672"
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"